<meta name="language" content="english" />
<meta name="robots" content="noindex,nofollow" />
<link rel="stylesheet" type="text/css" href="/archives/2010-04/css/styles.css" media="screen" />
<script type="text/javascript" src="/archives/2010-04/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="/archives/2010-04/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/archives/2010-04/js/jquery.lavalamp.1.3.2-min.js"></script>
<script type="text/javascript" src="/archives/2010-04/js/jquery.flyout.min.js"></script>
<script type="text/javascript" src="/archives/2010-04/js/effects.js"></script>