<h1>home</h1>
<ul>
	<li><a href="/archives/2010-04/" title="News">News</a></li>
	<li><a href="/archives/2010-04/about.php" title="About Me">About Me</a></li>
	<li><a href="/archives/2010-04/services.php" title="Design Services">Design Services</a></li>
	<li><a href="/archives/2010-04/resume.php" title="Resume">Resume</a></li>
	<li><a href="/archives/2010-04/old_news_09.php" title="Old News 2009">Old News</a></li>
</ul>
<h1>resources</h1>
<ul>
	<li><a href="/archives/2010-04/resources/links.php" title="Links">Links</a></li>
</ul>