<h1>portfolio</h1>
<ul>
	<li><a href="/archives/2010-04/portfolio/" title="Recent Additions">Recent Additions</a></li>
	<li><a href="/archives/2010-04/portfolio/websites.php" title="Websites">Websites</a></li>
	<li><a href="/archives/2010-04/portfolio/logos.php" title="Logo Designs">Logo Designs</a></li>
	<li><a href="/archives/2010-04/portfolio/printed.php" title="Printed Designs">Printed Designs</a></li>
</ul>
<h1>home</h1>
<ul>
	<li><a href="/archives/2010-04/" title="News">News</a></li>
	<li><a href="/archives/2010-04/resume.php" title="Resume">Resume</a></li>
</ul>
<h1>resources</h1>
<ul>
	<li><a href="/archives/2010-04/resources/links.php" title="Links">Links</a></li>
</ul>