<h1>external</h1>
<ul>
	<li><a href="http://www.google.com/analytics/" title="">Google Analytics</a></li>
	<li><a href="http://www.w3schools.com/" title="">W3Schools</a></li>
	<li><a href="http://jquery.com/" title="">jQuery</a></li>
</ul>
<a href="http://apollohosting.com/green/green-certified.bml?domain=scottbullochdesigns.com"><img src="http://images.apollohosting.com/green/badge-3.png" alt="Green Certified" class="centered" /></a>
<br />
<a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Strict" class="centered" /></a>
<br />
<a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS Level 2.1" class="centered" /></a>