<h1>resources</h1>
<ul>
	<li><a href="/archives/2010-04/resources/" title="Featured Resources">Featured Resources</a></li>
	<li><a href="/archives/2010-04/resources/javascript.php" title="JavaScript Resources">JavaScript</a></li>
	<li><a href="/archives/2010-04/resources/css.php" title="CSS Resources">CSS</a></li>
	<li><a href="/archives/2010-04/resources/xhtml.php" title="xHTML Resources">[X]HTML</a></li>
	<li><a href="/archives/2010-04/resources/links.php" title="Links">Links</a></li>
</ul>
<h1>home</h1>
<ul>
	<li><a href="/archives/2010-04/" title="News">News</a></li>
	<li><a href="/archives/2010-04/resume.php" title="Resume">Resume</a></li>
</ul>