<h1>contact</h1>
<ul>
	<li><a href="/archives/2010-04/contact/" title="Send A Message">Send A Message</a></li>
	<li><a href="/archives/2010-04/contact/social.php" title="Social Networks">Social Networks</a></li>
</ul>
<h1>home</h1>
<ul>
	<li><a href="/archives/2010-04/" title="News">News</a></li>
	<li><a href="/archives/2010-04/resume.php" title="Resume">Resume</a></li>
</ul>
<h1>resources</h1>
<ul>
	<li><a href="/archives/2010-04/resources/links.php" title="Links">Links</a></li>
</ul>