<div id="logo">
	<a href="http://www.scottbulloch.com/archives/2010-04/"><img src="/archives/2010-04/img/img01.gif" title="Scott Bulloch Designs" alt="logo" /></a>
</div>
<?php $active[$current] = "class='selectedLava'"; ?>
<div id="menu">
	<ul id="lavaLamp">
	<li <?php echo $active[1]; ?>><a href="/archives/2010-04/">home</a></li>
	<li <?php echo $active[2]; ?>><a href="/archives/2010-04/portfolio/">portfolio</a></li>
	<li <?php echo $active[3]; ?>><a href="/archives/2010-04/resources/">resources</a></li>
	<li <?php echo $active[4]; ?>><a href="/archives/2010-04/contact/">contact</a></li>
	</ul>
</div>